create table users
(
    id              integer generated by default as identity,
    activation_code varchar(255),
    email           varchar(255),
    active          boolean,
    locked          boolean,
    login           varchar(255),
    password        varchar(255),
    primary key (id)
);

create table roles
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table users_roles
(
    user_id integer not null,
    role_id integer not null
);

alter table users_roles
    add constraint fk_user_roles__roles_role_id foreign key (role_id) references roles;
alter table users_roles
    add constraint fk_user_roles__roles_user_id foreign key (user_id) references roles;

create table products
(
    id          integer generated by default as identity,
    count       integer,
    description varchar(255),
    filename    varchar(255),
    name        varchar(255),
    price       numeric(19, 2) check (price >= 100),
    primary key (id)
);

create table carts
(
    id     integer generated by default as identity,
    amount numeric(19, 2),
    primary key (id)
);

create table cart_rows
(
    id         integer generated by default as identity,
    amount     numeric(19, 2),
    count      integer,
    cart_id    integer,
    product_id integer,
    primary key (id)
);

alter table cart_rows
    add constraint fk_cart_row__carts_cart_id foreign key (cart_id) references carts;

alter table cart_rows
    add constraint fk_cart_row__products_product_id foreign key (product_id) references products;

create table clients
(
    id        integer generated by default as identity,
    firstname varchar(255),
    lastname  varchar(255),
    cart_id   integer,
    user_id   integer,
    primary key (id)
);

alter table clients
    add constraint fk_clients__carts_cart_id foreign key (cart_id)  references carts;

alter table clients
    add constraint kf_clients__users_user_id foreign key (user_id) references users;

create table orders
(
    id        integer generated by default as identity,
    amount    numeric(19, 2),
    status    varchar(255),
    client_id integer,
    primary key (id)
);

alter table orders
    add constraint fk_orders__clients_client_id foreign key (client_id) references clients;

create table order_rows
(
    id         integer generated by default as identity,
    amount     numeric(19, 2),
    count      integer,
    order_id   integer,
    product_id integer,
    primary key (id)
);

alter table order_rows
    add constraint fk_order_rows__orders_order_id foreign key (order_id) references orders;
alter table order_rows
    add constraint fk_order_rows__products_product_id foreign key (product_id) references products;